import os

output_dir = "Scripts/src/cpu/auto_gen_included_files"
filename = "isr_asm_gen.inc"
filepath = os.path.join(output_dir,filename)

os.makedirs(output_dir, exist_ok=True)

error_interrupts = [8,10,11,12,13,14,17,21]


with open(filepath, "w") as f:
  print(f"%ifndef ISR_CODES_ASM",file=f)
  print(f"%define ISR_CODES_ASM",file=f)
  print(";THIS FILE IS GENERATED BY PYTHON",file=f)
  for i in range(256):
    if error_interrupts.count(i):
      print(f"ISR_ERROR {i}",file=f)
    else:
      print(f"ISR_NO_ERROR {i}",file=f)
  print("%endif",file=f)
  