import os

output_dir = "Scripts/src/cpu/auto_gen_included_files"
filename = "isr_gen.c"
filepath = os.path.join(output_dir,filename)

os.makedirs(output_dir, exist_ok=True)

with open(filepath, "w") as f:
  print("//THIS FILE IS GENERATED BY PYTHON",file=f)
  print('#include "idt.h"',file=f)

  for i in range(256):
    print(f"extern void __attribute((cdecl)) ISR{i}();",file=f)

  print("void isr_initialize_gates()",file=f)
  print("{",file=f)

  for i in range(256):
    print(f"  idt_set_gate({i}, (uint32_t)ISR{i} & 0xFFFF, 0x08, IDT_FLAG_DPL_0 | IDT_FLAG_INTERRUPT_GATE_32BIT , ((uint32_t)ISR{i} >> 16) & 0xFFFF);", file=f)
  
  print("}",file=f)
